=== need4deed-org/be/src/server/schema/volunteer-api-id-part.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ApiVolunteerGetPart",
  "definitions": {
    "ApiVolunteerGetPart": {
      "type": "object",
      "properties": {
        "id": {
          "type": ["number", "string"]
        },
        "name": {
          "type": "string"
        },
        "avatarUrl": {
          "type": "string"
        },
        "status": {
          "$ref": "sdk-types.json#/definitions/VolunteerStateType"
        },
        "languages": {
          "type": "array",
          "items": {
            "$ref": "entity-types.json#/definitions/Language"
          }
        },
        "availability": {
          "type": "array",
          "items": {
            "$ref": "entity-types.json#/definitions/Timeslot"
          }
        },
        "activities": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "locations": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "address": {
          "$ref": "sdk-types.json#/definitions/Address"
        },
        "goodConductCertificate": {
          "$ref": "sdk-types.json#/definitions/DocumentStatusType"
        },
        "measlesVaccination": {
          "$ref": "sdk-types.json#/definitions/DocumentStatusType"
        },
        "infoAbout": {
          "type": "string"
        },
        "infoExperience": {
          "type": "string"
        },
        "timelineLogs": {
          "type": "array",
          "items": {
            "$ref": "sdk-types.json#/definitions/TimedText"
          }
        },
        "comments": {
          "type": "array",
          "items": {
            "$ref": "sdk-types.json#/definitions/TimedText"
          }
        },
        "opportunitiesApplied": {
          "type": "array",
          "items": {
            "$ref": "sdk-types.json#/definitions/Option"
          }
        },
        "opportunitiesMatched": {
          "type": "array",
          "items": {
            "$ref": "sdk-types.json#/definitions/Option"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== need4deed-org/be/public/data/agents.json
[
  {
    "id": 1,
    "firstName": "Uwe",
    "lastName": "Wolf",
    "email": "uwe.wolf@example.com",
    "phone": "+491784066101"
  },
  {
    "id": 2,
    "firstName": "Inga",
    "lastName": "Schwarz",
    "email": "inga.schwarz@example.com",
    "phone": "+491506163826"
  },
  {
    "id": 3,
    "firstName": "David",
    "lastName": "Schwarz",
    "email": "david.schwarz@example.com",
    "phone": "+491643250681"
  },
  {
    "id": 4,
    "firstName": "Klara",
    "lastName": "Fischer",
    "email": "klara.fischer@example.com",
    "phone": "+491657571681"
  },
  {
    "id": 5,
    "firstName": "Nils",
    "lastName": "Meyer",
    "email": "nils.meyer@example.com",
    "phone": "+491743591060"
  }
]
